# Generated by Django 3.0.6 on 2020-05-14 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhimChieuRap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('url', models.CharField(blank=True, default='', max_length=250)),
                ('image', models.CharField(blank=True, default='', max_length=250)),
                ('playtime', models.CharField(blank=True, default='', max_length=250)),
                ('sub', models.CharField(blank=True, default='', max_length=250)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('year', models.CharField(blank=True, max_length=250)),
                ('debut', models.CharField(blank=True, default='', max_length=100)),
                ('language', models.CharField(blank=True, default='', max_length=100)),
                ('business', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('url_movie', models.CharField(blank=True, default='', max_length=100)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phimmoi_chieurap.PhimChieuRap')),
            ],
        ),
    ]
