# Generated by Django 3.0.6 on 2020-05-14 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phimmoi_chieurap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='phimmoi_chieurap.PhimChieuRap'),
        ),
    ]
