# Generated by Django 3.0.6 on 2020-05-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phimmoi_chieurap', '0002_auto_20200514_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetail',
            name='url_movie_iframe',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='moviedetail',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
